export const productList = [
  {
    id: 1,
    productTitle: "stylish Handbags",
    category: "women",
    subCategory: "purse",
    brandName: "Mammon",
    pictures: "",
    shortDetails: "Mammon Women's stylish Handbags (LR-bib-blk)",
    description:
      "It contains two shoulder strap so you can carry it a shoulder bag as well lease allow little size deviation because everyone has their own measurement method.",
    rating: 1,
    stock: 16,
    price: 120.0,
    discount: 50,
    salePrice: 200.0,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["M", "L", "XL"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 2,
    productTitle: "Leather Formal Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 5,
    price: 2220.0,
    discount: 50,
    salePrice: 1200.0,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 3,
    productTitle: "Golden Golden Mirror",
    category: "women",
    subCategory: "goggles",
    brandName: "Vincent",
    pictures: "",
    shortDetails: "Golden Pink Golden Mirror Full Rim Wayfarer Shape",
    description:
      "Golden Pink Golden Mirror Full Rim Wayfarer Shape Medium (Size-53) Vincent Chase NOMADES VC S11109 - C2 Sunglasses",
    rating: 3,
    stock: 23,
    price: 1700.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 4,
    productTitle: "Fastrack Economy 2013",
    category: "men",
    subCategory: "watch",
    brandName: "Fastrack",
    pictures: "",
    shortDetails: "Watch",
    description:
      "Fastrack, a well renowned fashion brand brings an extravagant array of wrist watches for you this season. The Fastrack Economy 2013 Analog Black Dial Men's Watch has brought a significant raised the level of fashion trends in the era of mens accessories. The device is packed with excellent features and new technology to ensure that it gives you the best performance at all times.",
    rating: 5,
    stock: 42,
    price: 3500.0,
    discount: 50,
    salePrice: 2800.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: [],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 5,
    productTitle: "Digital Still Camera",
    category: "electric",
    subCategory: "camera",
    brandName: "philips",
    pictures: "",
    shortDetails: "Watch",
    description:
      "The ESee digital still camera lets you make high quality panorama pictures with photo stitching and captures 8 times closer to action with optical zoom. Get video in great details and make perfect shot with auto mode.",
    rating: 3,
    stock: 12,
    price: 55000.0,
    discount: 50,
    salePrice: 80000.0,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: [],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 6,
    productTitle: "Boat Headphones",
    category: "electric",
    subCategory: "Headphones",
    brandName: "boat",
    pictures: "",
    shortDetails: "Boat Rockerz 400 On-Ear Bluetooth Headphones (Carbon Black)",
    description:
      "Now just stop worrying about wires hanging from here and there. Wired is passé. Foldable/ Collapsible: Designed for people always on the move, easy storage and easy to carry. ",
    rating: 0,
    stock: 43,
    price: 1400.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: [],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 7,
    productTitle: "Anolog Men's Watch",
    category: "men",
    subCategory: "watch",
    brandName: "swisstyle",
    pictures: "",
    shortDetails: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
    description: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
    rating: 5,
    stock: 12,
    price: 7000.0,
    discount: 50,
    salePrice: 6700.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: [],
    tags: [],
    colors: [],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 8,
    productTitle: "black leisure shorts",
    category: "men",
    subCategory: "clothes",
    brandName: "jockey",
    pictures: "",
    shortDetails: "jockey graphite & black leisure shorts",
    description:
      "Fabric Details : 80% Cotton, 20% Polyester Premium Combed Cotton Rich fabric Straight Fit Durable broad waistband with flat inner drawstring",
    rating: 5,
    stock: 75,
    price: 2000.0,
    discount: 50,
    salePrice: 1300.0,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: [],
    tags: [],
    colors: [],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 9,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 54,
    price: 500,
    discount: 50,
    salePrice: 250,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 10,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 3,
    price: 500,
    discount: 2,
    salePrice: 350,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 11,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 8,
    price: 9000,
    discount: 23,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 12,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 0,
    stock: 13,
    price: 254,
    discount: 50,
    salePrice: 200,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 13,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 7,
    price: 600,
    discount: 40,
    salePrice: 650,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 14,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 12,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 15,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 12,
    price: 7800,
    discount: 50,
    salePrice: 7000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 16,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 55,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 17,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 77,
    price: 2220,
    discount: 50,
    salePrice: 1200,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 18,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 32,
    price: 8000,
    discount: 20,
    salePrice: 7500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 19,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 12,
    price: 28000,
    discount: 12,
    salePrice: 25000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 20,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 8,
    price: 19000,
    discount: 12,
    salePrice: 18000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 21,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 4,
    price: 5800,
    discount: 50,
    salePrice: 5000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 22,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 2,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 23,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 6,
    price: 7000,
    discount: 50,
    salePrice: 6500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 24,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 44,
    price: 8000,
    discount: 50,
    salePrice: 18000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 25,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 23,
    price: 7000,
    discount: 50,
    salePrice: 6500,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 26,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 56,
    price: 6800,
    discount: 50,
    salePrice: 6000,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 27,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 345,
    price: 6900,
    discount: 50,
    salePrice: 6400,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 28,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 4,
    price: 8700,
    discount: 50,
    salePrice: 2800,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 29,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 456,
    price: 7000,
    discount: 50,
    salePrice: 6500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 30,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 45,
    price: 6800,
    discount: 50,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 31,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 9500,
    discount: 50,
    salePrice: 9000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 32,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 34,
    price: 8000,
    discount: 50,
    salePrice: 7500,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 33,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 1,
    price: 7500,
    discount: 50,
    salePrice: 7000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 34,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 6,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 35,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 2,
    price: 6500,
    discount: 50,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 36,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 56,
    price: 12000,
    discount: 50,
    salePrice: 11500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 37,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 3,
    price: 9999,
    discount: 50,
    salePrice: 8888,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 38,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 5,
    price: 7777,
    discount: 50,
    salePrice: 6666,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 39,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 3,
    price: 5555,
    discount: 50,
    salePrice: 4444,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 40,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 4,
    price: 6800,
    discount: 40,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 41,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 654,
    price: 9400,
    discount: 12,
    salePrice: 9000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 42,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 45,
    price: 7800,
    discount: 40,
    salePrice: 7000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 43,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 756,
    price: 9000,
    discount: 40,
    salePrice: 8500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 44,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 56,
    price: 9000,
    discount: 12,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 45,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 567,
    price: 1258,
    discount: 2,
    salePrice: 1200,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 46,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 34,
    price: 6500,
    discount: 10,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 47,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 324,
    price: 17000,
    discount: 40,
    salePrice: 15000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 48,
    productTitle: "Leather Formal Shoes",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 94000,
    discount: 25,
    salePrice: 88000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  },
  {
    id: 49,
    productTitle: "Daily Wear Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 345,
    price: 1000.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" }
    ]
  }
];

export default {
  productList
};
